### ISSUE TITLE
npm run build我这里报错了.麻烦看看.

### ISSUE THREAD

**Issue by lileltp** [qbright/vue2_vuex2_webpack2_ssr#1]
ERROR in Entry module not found: Error: Can't resolve 'babel' in '/Downloads/vue2_vuex2_webpack2_ssr-master'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
  You need to specify 'babel-loader' instead of 'babel'.

**Comment by qbright** [comment]
@lileltp 最后一行写着 在loader配置里面用 babel-loader 替换babel,试试看，估计是webpack的版本不同或者是你那个库没有安装对的问题
